[package]
name = "lib_jsl"
version = "0.1.0"
edition = "2024"

[dependencies]
num = "*"
rand = "*"
rand_distr = "*" 
ndarray = { version = "*", features = ["blas"] }
ndarray-linalg = { version = "*", features = ["intel-mkl-static"] }   